version: '3'
services:
  emoine:
    build: ./
    entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306
    command: ./Emoine
    ports:
      - 3050:80
    depends_on:
      - mysql
    environment:
      - CLIENT_ID=I62ZG0yeAZUFmFKgWAfFRRuA8blN5IxlnnJd
      - SECRET=secret
      - ADMINS=e05f733f-dccc-47dc-9f56-c8eb38306284,132187b3-fae6-4c4c-9fe7-c1399c03e533,e05f733f-dccc-47dc-9f56-c8eb38306284,62aea407-1df4-426a-82a9-c5d26686b860, 88bbac6b-decc-42af-ab06-31a96e992028

  mysql:
    image: mariadb:10.6.4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: emoine
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    expose:
      - "3306"
