version: '3'
services:
  emoine:
    build: .
    ports:
      - 80:80
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: emoine
    expose:
      - "3306"
    ports:
      - 3306:3306