version: '3'
services:
  emoine:
    build: ./
    entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306
    ports:
      - 80:80
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.0.19
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    expose:
      - "3306"