name: CI (client)

on:
  push:
    branches:
      - 'master'
  pull_request:

defaults:
  run:
    working-directory: client

jobs:
  packages:
    name: Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npm run build
        env:
          NODE_ENV: production
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npm run lint
  typeCheck:
    name: Type Check
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npm run type-check
